# Generated by Django 5.1.3 on 2024-12-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
