# Generated by Django 5.1.3 on 2024-12-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_note'),
        ('reg', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
